export const KINS_COVERS_DATA = [
  {
    id: "cover-1",
    title: "Everlong",
    originalArtist: "Foo Fighters",
    category: "full-band",
    categoryLabel: "Full Band",
    thumbnail: "https://img.youtube.com/vi/eBG7P-K-r1Y/hqdefault.jpg",
    embedUrl: "https://www.youtube.com/embed/eBG7P-K-r1Y?autoplay=1",
    platform: "youtube",
    platformLabel: "YouTube",
    platformIcon: "fa-brands fa-youtube",
    watchUrl: "https://www.youtube.com/watch?v=eBG7P-K-r1Y",
    commentUrl: "https://www.youtube.com/watch?v=eBG7P-K-r1Y&lc=",
    followUrl: "https://youtube.com/@KinsBandOfficial",
    commentCount: 42,
    isLatest: true
  },
  {
    id: "cover-2",
    title: "Just Like Heaven",
    originalArtist: "The Cure",
    category: "full-band",
    categoryLabel: "Full Band",
    thumbnail: "https://img.youtube.com/vi/n3nPiBai68M/hqdefault.jpg",
    embedUrl: "https://www.youtube.com/embed/n3nPiBai68M?autoplay=1",
    platform: "youtube",
    platformLabel: "YouTube",
    platformIcon: "fa-brands fa-youtube",
    watchUrl: "https://www.youtube.com/watch?v=n3nPiBai68M",
    commentUrl: "https://www.youtube.com/watch?v=n3nPiBai68M&lc=",
    followUrl: "https://youtube.com/@KinsBandOfficial",
    commentCount: 28,
    isLatest: true
  },
  {
    id: "cover-3",
    title: "Buddy Holly",
    originalArtist: "Weezer",
    category: "acoustic",
    categoryLabel: "Acoustic",
    thumbnail: "https://img.youtube.com/vi/kemivUKb4f4/hqdefault.jpg",
    embedUrl: "https://www.youtube.com/embed/kemivUKb4f4?autoplay=1",
    platform: "youtube",
    platformLabel: "YouTube",
    platformIcon: "fa-brands fa-youtube",
    watchUrl: "https://www.youtube.com/watch?v=kemivUKb4f4",
    commentUrl: "https://www.youtube.com/watch?v=kemivUKb4f4&lc=",
    followUrl: "https://youtube.com/@KinsBandOfficial",
    commentCount: 19,
    isLatest: true
  },
  {
    id: "cover-4",
    title: "Common People",
    originalArtist: "Pulp",
    category: "shorts",
    categoryLabel: "Shorts",
    thumbnail: "https://img.youtube.com/vi/yuTMWgOduFM/hqdefault.jpg",
    embedUrl: "https://www.youtube.com/embed/yuTMWgOduFM?autoplay=1",
    platform: "youtube",
    platformLabel: "YouTube",
    platformIcon: "fa-brands fa-youtube",
    watchUrl: "https://www.youtube.com/watch?v=yuTMWgOduFM",
    commentUrl: "https://www.youtube.com/watch?v=yuTMWgOduFM&lc=",
    followUrl: "https://youtube.com/@KinsBandOfficial",
    commentCount: 35,
    isLatest: true
  },
  {
    id: "cover-5",
    title: "Jane!",
    originalArtist: "The Long Faces",
    category: "full-band",
    categoryLabel: "Full Band",
    thumbnail: "https://img.youtube.com/vi/eBG7P-K-r1Y/hqdefault.jpg",
    embedUrl: "https://www.youtube.com/embed/eBG7P-K-r1Y?autoplay=1",
    platform: "youtube",
    platformLabel: "YouTube",
    platformIcon: "fa-brands fa-youtube",
    watchUrl: "https://www.youtube.com/watch?v=eBG7P-K-r1Y",
    commentUrl: "https://www.youtube.com/watch?v=eBG7P-K-r1Y&lc=",
    followUrl: "https://youtube.com/@KinsBandOfficial",
    commentCount: 14,
    isLatest: false
  },
  {
    id: "cover-6",
    title: "Boys Don't Cry",
    originalArtist: "The Cure",
    category: "acoustic",
    categoryLabel: "Acoustic",
    thumbnail: "https://img.youtube.com/vi/n3nPiBai68M/hqdefault.jpg",
    embedUrl: "https://www.youtube.com/embed/n3nPiBai68M?autoplay=1",
    platform: "youtube",
    platformLabel: "YouTube",
    platformIcon: "fa-brands fa-youtube",
    watchUrl: "https://www.youtube.com/watch?v=n3nPiBai68M",
    commentUrl: "https://www.youtube.com/watch?v=n3nPiBai68M&lc=",
    followUrl: "https://youtube.com/@KinsBandOfficial",
    commentCount: 22,
    isLatest: false
  }
];
